### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by The-Gupta** [mdtux89/amr-eager#3]
Could you test it on Windows and mention the installation steps?

**Comment by mdtux89** [comment]
No, I have no plan to support Windows and I'm not even sure if you can install all tools required in Windows. My suggestion for you is to use Linux. Even for Torch only is not straight-forward to install on Windows but you can try starting from here https://github.com/torch/torch7/wiki/Windows#running-torch-on-windows. Note that the first suggestion is to install an Ubuntu on a virtual machine :)
